name: autofix.ci

on:
  pull_request:
    paths:
      - 'pkgs/**'

permissions: {}

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate registry.yaml
        run: make generate

      - uses: autofix-ci/action@v1
